services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=shokhjahon1199

    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db

    ports:
      - "8000:8000"
    volumes:
      - .:/code