# Generated by Django 4.2.3 on 2023-07-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=9, verbose_name='Yili')),
                ('name', models.CharField(max_length=255, verbose_name='Mukofot')),
                ('about', models.CharField(max_length=255, verbose_name='Mukofot haqida')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=9, verbose_name='Yili')),
                ('topic', models.CharField(max_length=255, verbose_name='Mavzusi')),
                ('desc', models.CharField(max_length=255, verbose_name='Mavzu haqida')),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
    ]
