# Generated by Django 4.2.3 on 2023-07-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=9, verbose_name='Yili')),
                ('topic', models.CharField(max_length=255, verbose_name='Mavzusi')),
                ('desc', models.CharField(max_length=255, verbose_name='Mavzu haqida')),
            ],
            options={
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
