# Generated by Django 4.2.3 on 2023-07-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_rename_topic_experience_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='about',
        ),
    ]
