# Generated by Django 4.2.3 on 2023-07-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_awards_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='where',
            field=models.CharField(max_length=255, null=True, verbose_name='Mukofot haqida'),
        ),
    ]
